site_name: SQLAlchemy CRUD Plus
site_description: 现代化的 SQLAlchemy 2.0 异步 CRUD 操作库，为 Python 开发者提供简洁、强大、类型安全的数据库操作体验
site_url: https://fastapi-practices.github.io/sqlalchemy-crud-plus
site_author: FastAPI Practices
repo_name: sqlalchemy-crud-plus
repo_url: https://github.com/fastapi-practices/sqlalchemy-crud-plus

nav:
  - 首页: index.md
  - 安装: installing.md
  - 基础用法:
      - 快速开始: getting-started/quick-start.md
      - CRUD 操作: usage/crud.md
  - 高级用法:
      - 过滤条件: advanced/filter.md
      - 关系查询: relationships/overview.md
      - 事务控制: advanced/transaction.md
  - API 参考: api/crud-plus.md
  - 更新日志: changelog.md

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.suggest
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            filters: ["!^_"]
            show_root_heading: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fastapi-practices/sqlalchemy-crud-plus
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/yNN3wTbVAC
      name: Discord

extra_css:
  - "extra/custom.css"

copyright: |
  &copy; 2024 - 2025 FastAPI Practices - 为爱发电
